export interface SDKMessage {
  type: Exclude<string, 'control_request' | 'control_response' | 'control_cancel_request' | 'partial_assistant'>
  subtype?: string
  role?: string
  content?: unknown
  model?: string
  stop_reason?: string | null
  usage?: Record<string, unknown>
  [key: string]: unknown
}

export interface SDKUserMessage extends SDKMessage {
  type: 'human' | 'user'
  role: 'user'
  content: string | unknown[]
}

export interface SDKAssistantMessage extends SDKMessage {
  type: 'assistant'
  role: 'assistant'
  content: unknown[]
}

export interface SDKResult {
  type: 'result'
  subtype: string
  [key: string]: unknown
}

export interface SDKResultSuccess extends SDKResult {
  subtype: 'success'
  duration_ms?: number
  duration_api_ms?: number
  is_error?: boolean
  num_turns?: number
  session_id?: string
  total_cost_usd?: number
  usage?: Record<string, unknown>
}

export interface SDKResultError extends SDKResult {
  subtype: 'error'
  error: string
}

export type HookEvent = typeof HOOK_EVENTS_ARRAY[number]
const HOOK_EVENTS_ARRAY = [
  'PreToolUse', 'PostToolUse', 'PostToolUseFailure', 'Notification',
  'UserPromptSubmit', 'SessionStart', 'SessionEnd', 'Stop', 'StopFailure',
  'SubagentStart', 'SubagentStop', 'PreCompact', 'PostCompact',
  'PermissionRequest', 'PermissionDenied', 'Setup', 'TeammateIdle',
  'TaskCreated', 'TaskCompleted', 'Elicitation', 'ElicitationResult',
  'ConfigChange', 'WorktreeCreate', 'WorktreeRemove', 'InstructionsLoaded',
  'CwdChanged', 'FileChanged',
] as const

export type ExitReason = 'clear' | 'resume' | 'logout' | 'prompt_input_exit' | 'other' | 'bypass_permissions_disabled'

// Types generated from Zod schemas in coreSchemas.ts
// These should be regenerated by scripts/generate-sdk-types.ts when schemas change

export interface ModelUsage {
  inputTokens: number
  outputTokens: number
  cacheReadInputTokens: number
  cacheCreationInputTokens: number
  webSearchRequests: number
  costUSD: number
  contextWindow: number
  maxOutputTokens: number
}

export interface PermissionResult {
  behavior: 'allow' | 'deny'
  updatedInput?: Record<string, unknown>
  updatedPermissions?: PermissionUpdate[]
  toolUseID?: string
  decisionClassification?: string
  message?: string
  interrupt?: boolean
}

export interface PermissionUpdate {
  permission: string
  value: 'allow' | 'deny'
}

export interface ModelInfo {
  value: string
  displayName: string
  description: string
  supportsEffort?: boolean
  supportedEffortLevels?: ('low' | 'medium' | 'high' | 'max')[]
  supportsAdaptiveThinking?: boolean
  supportsFastMode?: boolean
  supportsAutoMode?: boolean
}

export type SDKStatus = 'compacting' | null

export interface RewindFilesResult {
  canRewind: boolean
  error?: string
  filesChanged?: string[]
  insertions?: number
  deletions?: number
}

export interface McpServerConfigForProcessTransport {
  command: string
  args?: string[]
  env?: Record<string, string>
  cwd?: string
  [key: string]: unknown
}

export interface McpServerStatus {
  name: string
  status: 'connected' | 'failed' | 'needs-auth' | 'pending' | 'disabled'
  serverInfo?: { name: string; version?: string }
  error?: string
  config?: McpServerConfigForProcessTransport
  scope?: string
  tools?: McpToolInfo[]
  capabilities?: Record<string, unknown>
}

export interface McpToolInfo {
  name: string
  description?: string
  inputSchema?: Record<string, unknown>
  annotations?: Record<string, unknown>
}

// Hook input types
export interface BaseHookInput {
  session_id: string
  transcript_path: string
  cwd: string
  permission_mode?: string
  agent_id?: string
  agent_type?: string
}

export type HookInput =
  | PreToolUseHookInput
  | PostToolUseHookInput
  | PostToolUseFailureHookInput
  | PermissionDeniedHookInput
  | NotificationHookInput
  | UserPromptSubmitHookInput
  | SessionStartHookInput
  | SessionEndHookInput
  | StopHookInput
  | StopFailureHookInput
  | SubagentStartHookInput
  | SubagentStopHookInput
  | PreCompactHookInput
  | PostCompactHookInput
  | SetupHookInput
  | TeammateIdleHookInput
  | TaskCreatedHookInput
  | TaskCompletedHookInput
  | ElicitationHookInput
  | ElicitationResultHookInput
  | ConfigChangeHookInput
  | BaseHookInput

export interface PreToolUseHookInput extends BaseHookInput {
  hook_event_name: 'PreToolUse'
  tool_name: string
  tool_input: unknown
  tool_use_id: string
}

export interface PostToolUseHookInput extends BaseHookInput {
  hook_event_name: 'PostToolUse'
  tool_name: string
  tool_input: unknown
  tool_response: unknown
  tool_use_id: string
}

export interface PostToolUseFailureHookInput extends BaseHookInput {
  hook_event_name: 'PostToolUseFailure'
  tool_name: string
  tool_input: unknown
  tool_response: unknown
  tool_use_id: string
  error: string
}

export interface PermissionDeniedHookInput extends BaseHookInput {
  hook_event_name: 'PermissionDenied'
  tool_name: string
  tool_input: unknown
  tool_use_id: string
}

export interface NotificationHookInput extends BaseHookInput {
  hook_event_name: 'Notification'
  message: string
}

export interface UserPromptSubmitHookInput extends BaseHookInput {
  hook_event_name: 'UserPromptSubmit'
  prompt: string
}

export interface SessionStartHookInput extends BaseHookInput {
  hook_event_name: 'SessionStart'
}

export interface SessionEndHookInput extends BaseHookInput {
  hook_event_name: 'SessionEnd'
  exit_reason: ExitReason
}

export interface StopHookInput extends BaseHookInput {
  hook_event_name: 'Stop'
}

export interface StopFailureHookInput extends BaseHookInput {
  hook_event_name: 'StopFailure'
  error: string
}

export interface SubagentStartHookInput extends BaseHookInput {
  hook_event_name: 'SubagentStart'
  agent_id: string
  agent_type: string
}

export interface SubagentStopHookInput extends BaseHookInput {
  hook_event_name: 'SubagentStop'
  agent_id: string
  agent_type: string
}

export interface PreCompactHookInput extends BaseHookInput {
  hook_event_name: 'PreCompact'
}

export interface PostCompactHookInput extends BaseHookInput {
  hook_event_name: 'PostCompact'
}

export interface SetupHookInput extends BaseHookInput {
  hook_event_name: 'Setup'
}

export interface TeammateIdleHookInput extends BaseHookInput {
  hook_event_name: 'TeammateIdle'
}

export interface TaskCreatedHookInput extends BaseHookInput {
  hook_event_name: 'TaskCreated'
}

export interface TaskCompletedHookInput extends BaseHookInput {
  hook_event_name: 'TaskCompleted'
}

export interface ElicitationHookInput extends BaseHookInput {
  hook_event_name: 'Elicitation'
  message: string
}

export interface ElicitationResultHookInput extends BaseHookInput {
  hook_event_name: 'ElicitationResult'
}

export interface ConfigChangeHookInput extends BaseHookInput {
  hook_event_name: 'ConfigChange'
  config_path: string
}

// Hook output types
export interface SyncHookJSONOutput {
  decision?: 'block' | 'approve' | 'ignore'
  reason?: string
  suppressOutput?: boolean
  continue?: boolean
  [key: string]: unknown
}

export interface AsyncHookJSONOutput {
  decision?: 'block' | 'approve' | 'ignore'
  reason?: string
  suppressOutput?: boolean
  [key: string]: unknown
}

export type HookJSONOutput = SyncHookJSONOutput | AsyncHookJSONOutput

// Convenience aliases for commonly used names
export type PermissionMode = string
export type ApiKeySource = string

// SDK message subtypes that code imports
export interface SDKResultMessage extends SDKMessage {
  type: 'result'
  subtype: 'success' | 'error'
  session_id?: string
  duration_ms?: number
  total_cost_usd?: number
  usage?: Record<string, unknown>
}

export interface SDKSessionInfo {
  session_id: string
  model?: string
  created_at?: number
  updated_at?: number
  [key: string]: unknown
}

export interface SDKCompactBoundaryMessage extends SDKMessage {
  type: 'system'
  subtype: 'compact_boundary'
}

export interface SDKPermissionDenial extends SDKMessage {
  type: 'system'
  subtype: 'permission_denial'
  [key: string]: unknown
}

export interface SDKRateLimitInfo extends SDKMessage {
  type: 'system'
  subtype: 'rate_limit'
  [key: string]: unknown
}

export interface SDKToolProgressMessage extends SDKMessage {
  type: 'progress'
  tool_use_id: string
  data?: unknown
}

// Additional hook input types used by code
export interface CwdChangedHookInput extends BaseHookInput {
  hook_event_name: 'CwdChanged'
  previous_cwd?: string
}

export interface FileChangedHookInput extends BaseHookInput {
  hook_event_name: 'FileChanged'
  changed_files?: string[]
}

export interface InstructionsLoadedHookInput extends BaseHookInput {
  hook_event_name: 'InstructionsLoaded'
}

export interface PermissionRequestHookInput extends BaseHookInput {
  hook_event_name: 'PermissionRequest'
  tool_name: string
  tool_input: Record<string, unknown>
}

export interface WorktreeCreateHookInput extends BaseHookInput {
  hook_event_name: 'WorktreeCreate'
  worktree_path?: string
}

export interface WorktreeRemoveHookInput extends BaseHookInput {
  hook_event_name: 'WorktreeRemove'
  worktree_path?: string
}

// Aliases for backward compat with old import names
export type SDKAssistantMessageError = 'authentication_failed' | 'billing_error' | 'rate_limit' | 'invalid_request' | 'server_error' | 'unknown' | 'max_output_tokens'
export type SDKPartialAssistantMessage = SDKAssistantMessage
export type SDKStatusMessage = SDKUserMessage
export type SDKSystemMessage = SDKUserMessage
export type SDKUserMessageReplay = SDKUserMessage
